In [1]:
import pandas as pd

In [117]:
df= pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], columns=["A","B","C"], index=['x','y','z','k'], dtype='float32')
df

      A     B     C
x   1.0   2.0   3.0
y   4.0   5.0   6.0
z   7.0   8.0   9.0
k  10.0  11.0  12.0

In [14]:
df.index.tolist()

['x', 'y', 'z']

In [118]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, x to k
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      float32
 1   B       4 non-null      float32
 2   C       4 non-null      float32
dtypes: float32(3)
memory usage: 84.0 bytes

In [20]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [119]:
df.nunique()

A    4
B    4
C    4
dtype: int64

In [28]:
df.shape

(4, 3)

In [30]:
df.size

12

LOADİNG İN DATAFRAMES FROM FİLES

In [31]:
df= pd.read_csv('./data/coffee.csv')

In [35]:
df.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [38]:
results=pd.read_parquet('./data/results.parquet')

In [39]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [40]:
olympics_data= pd.read_excel('./data/olympics.xlsx')

In [42]:
olympics_data.head(
)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [44]:
results=pd.read_parquet('./data/results.parquet')
bios=pd.read_csv('./data/bios_new.csv')
coffee=pd.read_csv('./data/coffee.csv')

In [123]:
df.to_csv('./data/mete.csv', index=False) # to save

ACCESSSİNG DATA WİTH PANDAS

In [49]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [59]:
coffee.sample(5 ,random_state=14) # to random sample

          Day Coffee Type  Units Sold
5   Wednesday       Latte          25
3     Tuesday       Latte          20
12     Sunday    Espresso          45
1      Monday       Latte          15
0      Monday    Espresso          25

loc iloc   look ve indexlook
df.loc[#rows ,#columns]

In [74]:
coffee.loc[0]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [68]:
coffee.loc[3:5, ['Day','Coffee Type']]

         Day Coffee Type
3    Tuesday       Latte
4  Wednesday    Espresso
5  Wednesday       Latte

In [73]:
coffee.iloc[2:6,  0:3]

         Day Coffee Type  Units Sold
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25

In [75]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [81]:
coffee.index=coffee['Day']

In [77]:
coffee

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35
Wednesday  Wednesday       Latte          25
Thursday    Thursday    Espresso          40
Thursday    Thursday       Latte          30
Friday        Friday    Espresso          45
Friday        Friday       Latte          35
Saturday    Saturday    Espresso          45
Saturday    Saturday       Latte          35
Sunday        Sunday    Espresso          45
Sunday        Sunday       Latte          35

In [83]:
coffee.loc['Monday':'Wednesday', 'Units Sold']

Day
Monday       25
Monday       15
Tuesday      30
Tuesday      20
Wednesday    35
Wednesday    25
Name: Units Sold, dtype: int64

In [84]:
coffee=pd.read_csv('./data/coffee.csv')

In [ ]:
coffee.loc[6,'Units Sold']=30

In [92]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          30
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [106]:
coffee.loc[4, 'Units Sold']=30
coffee.sort_values(['Units Sold','Day'], ascending=[0,0])

          Day Coffee Type  Units Sold
12     Sunday    Espresso          45
10   Saturday    Espresso          45
8      Friday    Espresso          45
13     Sunday       Latte          35
11   Saturday       Latte          35
9      Friday       Latte          35
4   Wednesday    Espresso          30
2     Tuesday    Espresso          30
6    Thursday    Espresso          30
7    Thursday       Latte          30
5   Wednesday       Latte          25
0      Monday    Espresso          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [113]:
for index,row in coffee.iterrows():
    print(index)
    print(row[['Day', 'Units Sold']])
    print("\n")

0
Day           Monday
Units Sold        25
Name: 0, dtype: object


1
Day           Monday
Units Sold        15
Name: 1, dtype: object


2
Day           Tuesday
Units Sold         30
Name: 2, dtype: object


3
Day           Tuesday
Units Sold         20
Name: 3, dtype: object


4
Day           Wednesday
Units Sold           30
Name: 4, dtype: object


5
Day           Wednesday
Units Sold           25
Name: 5, dtype: object


6
Day           Thursday
Units Sold          30
Name: 6, dtype: object


7
Day           Thursday
Units Sold          30
Name: 7, dtype: object


8
Day           Friday
Units Sold        45
Name: 8, dtype: object


9
Day           Friday
Units Sold        35
Name: 9, dtype: object


10
Day           Saturday
Units Sold          45
Name: 10, dtype: object


11
Day           Saturday
Units Sold          35
Name: 11, dtype: object


12
Day           Sunday
Units Sold        45
Name: 12, dtype: object


13
Day           Sunday
Units Sold        35
Name: 13, dtype: object

In [125]:
df=pd.read_excel('./data/olympics.xlsx')

In [126]:
df

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [130]:
df.columns.tolist()

['athlete_id',
 'name',
 'born_date',
 'born_city',
 'born_region',
 'born_country',
 'NOC',
 'height_cm',
 'weight_kg',
 'died_date']

In [131]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 18.5 MB

In [139]:
df.loc[(df['height_cm']>210) & (df['weight_kg']>130)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
6270,6298,Hu Zhangbao,1963-04-05,NaN,NaN,NaN,People's Republic of China,216.0,135.0,NaN
6420,6451,Jānis Krūmiņš,1930-01-30,Cēsis,Cēsu novads,LAT,Soviet Union,218.0,141.0,1994-11-20
6504,6537,Luc Longley,1969-01-19,Melbourne,Victoria,AUS,Australia,220.0,135.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
33129,33379,Peter Adelaar,1947-02-26,Amsterdam,Noord-Holland,NED,Netherlands,213.0,135.0,2004-10-14
33936,34200,Pak Jong-Gil,1951-01-14,NaN,NaN,NaN,Democratic People's Republic of Korea,213.0,163.0,NaN
59248,59674,Adam Sandurski,1953-02-08,NaN,NaN,NaN,Poland,214.0,135.0,NaN
89062,89773,Todd MacCulloch,1976-01-27,Winnipeg,Manitoba,CAN,Canada,213.0,132.0,NaN
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN

In [144]:
df[df['height_cm']>215][['name','born_date']].head(12)

                       name   born_date
5089     Viktor Pankrashkin  1957-06-19
5583   Paulinho Villas Boas  1963-01-26
5673         Gunther Behnke  1963-01-19
5716               Uwe Blab  1962-03-26
5781         Tommy Burleson  1952-02-24
5796          Andy Campbell  1956-07-21
6223            Lars Hansen  1954-09-27
6270            Hu Zhangbao  1963-04-05
6409       Sergey Kovalenko  1947-08-11
6420          Jānis Krūmiņš  1930-01-30
6504            Luc Longley  1969-01-19
6722       Shaquille O'Neal  1972-03-06

In [149]:
df[(df['height_cm']>215) & (df['born_country']=='USA')][['name','athlete_id']]

                    name  athlete_id
5781      Tommy Burleson        5804
6722    Shaquille O'Neal        6755
6937      David Robinson        6972
123850    Tyson Chandler      126093

In [158]:
df[(df['name'].str.contains('keith | patrick | james', case=False))]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
578,580,Harold James,1868-01-31,NaN,NaN,NaN,Great Britain,NaN,NaN,1948-10-19
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3255,3267,Ken James,1945-01-19,Curwensville,Pennsylvania,USA,Australia,190.0,82.0,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
4772,4790,Moses James,1968-06-25,NaN,NaN,NaN,Nigeria,170.0,63.0,NaN
...,...,...,...,...,...,...,...,...,...,...
126191,128541,Marvin James,1989-10-27,Reichenbach,Bern,SUI,Switzerland,171.0,69.0,NaN
127756,130231,Becky James,1991-11-29,Abergavenny,Wales,GBR,Great Britain,171.0,66.0,NaN
130056,132709,Renick James,1987-08-21,Belize City,Belize,BIZ,Belize,180.0,91.0,NaN
139469,142942,Scott James Fiti,1995-07-17,NaN,NaN,NaN,Federated States of Micronesia,NaN,NaN,NaN
142133,145730,Kirstie James,1989-05-25,Auckland,Auckland,NZL,New Zealand,175.0,NaN,NaN

In [169]:
df[(df['born_date'].str.contains('1973'))]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
26,27,Christophe Legoût,1973-08-06,Montbéliard,Doubs,FRA,France,177.0,75.0,NaN
74,75,Simon Archer,1973-06-27,Leamington Spa,England,GBR,Great Britain,189.0,86.0,NaN
114,115,Greg Rusedski,1973-09-06,Montréal,Québec,CAN,Great Britain,190.0,88.0,NaN
130,131,Barbara Rittner,1973-04-25,Krefeld,Nordrhein-Westfalen,GER,Germany,173.0,65.0,NaN
131,132,Elke Schall-Wosik,1973-07-19,Speyer,Rheinland-Pfalz,GER,Germany,180.0,68.0,NaN
...,...,...,...,...,...,...,...,...,...,...
129860,132507,Scott Hend,1973-08-15,Townsville,Queensland,AUS,Australia,180.0,82.0,NaN
130557,133246,Diego Colorado,1973-08-31,Jardin,Antioquia,COL,Colombia,171.0,57.0,NaN
131237,134010,Spencer Wilton,1973-02-01,Ipswich,England,GBR,Great Britain,183.0,83.0,NaN
131928,134770,Shingo Katayama,1973-01-31,Chikusei,Ibaraki,JPN,Japan,168.0,73.0,NaN
133224,136161,Saif Bin Futtais,1973-09-02,Dubai,Dubai,UAE,United Arab Emirates,174.0,90.0,NaN

In [178]:
df[(df['born_country'].isin(['FRA','USA']))]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145467,149194,Elisa Nakab,1998-05-08,Briançon,Hautes-Alpes,FRA,Italy,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18

In [182]:
df.query("born_country == 'USA'")

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145445,149168,Kristen Santos,1994-11-02,Fairfield,Connecticut,USA,United States,NaN,NaN,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN

In [201]:
coffee['price']=10

In [ ]:
import numpy as np
coffee['new_price']=np.where(coffee['Coffee Type']=='Esperesso' , 3.99 , 5.99)
coffee.drop(columns='price' , inplace=True)

In [216]:
coffee.drop(index=[0,1,2,3])

          Day Coffee Type  Units Sold  new_price
4   Wednesday    Espresso          30       5.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          30       5.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       5.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       5.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       5.99
13     Sunday       Latte          35       5.99

In [ ]:
coffee.iloc[2,2]=30
coffee_new=coffee.copy()

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       5.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       5.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          30       5.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          30       5.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       5.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       5.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       5.99
13     Sunday       Latte          35       5.99

In [231]:
coffee_new.iloc[2,2]=15
coffee_new
coffee

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       5.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       5.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          30       5.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          30       5.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       5.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       5.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       5.99
13     Sunday       Latte          35       5.99

In [232]:
coffee['revenue']= coffee['new_price'] * coffee['Units Sold']

In [233]:
coffee

          Day Coffee Type  Units Sold  new_price  revenue
0      Monday    Espresso          25       5.99   149.75
1      Monday       Latte          15       5.99    89.85
2     Tuesday    Espresso          30       5.99   179.70
3     Tuesday       Latte          20       5.99   119.80
4   Wednesday    Espresso          30       5.99   179.70
5   Wednesday       Latte          25       5.99   149.75
6    Thursday    Espresso          30       5.99   179.70
7    Thursday       Latte          30       5.99   179.70
8      Friday    Espresso          45       5.99   269.55
9      Friday       Latte          35       5.99   209.65
10   Saturday    Espresso          45       5.99   269.55
11   Saturday       Latte          35       5.99   209.65
12     Sunday    Espresso          45       5.99   269.55
13     Sunday       Latte          35       5.99   209.65

In [234]:
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,Grande,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,Average,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,Average,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,Average,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,Grande,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,Average,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,Average,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,Short,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,Average,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,Grande,NaN,2003-10-20

In [236]:
bios_new=bios.copy()
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,Grande,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,Average,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,Average,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,Average,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,Grande,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,Average,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,Average,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,Short,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,Average,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,Grande,NaN,2003-10-20

In [242]:
bios_new['first_name']= bios['name'].str.split(' ').str[0]
bios_new.query('first_name == "Keith"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,Grande,NaN,NaN,Keith
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,Average,51.0,1999-12-31,Keith
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,Grande,85.0,NaN,Keith
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,Grande,NaN,1993-01-09,Keith
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,Grande,NaN,1973-02-22,Keith
...,...,...,...,...,...,...,...,...,...,...,...
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,Grande,93.0,NaN,Keith
102227,103168,Keith Beavers,1983-02-09,London,Ontario,CAN,Canada,Grande,75.0,NaN,Keith
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,Grande,NaN,2013-11-15,Keith
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,Average,95.0,NaN,Keith
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,Average,78.0,NaN,Keith

In [261]:

bios_new['born_datenew']=pd.to_datetime(bios_new['born_date'])
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datenew,year
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,Grande,NaN,1960-10-02,Jean-François,1886-12-12,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,Average,76.0,NaN,Arnaud,1969-04-01,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,Average,76.0,1994-07-17,Jean,1898-08-13,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,Average,64.0,1978-03-20,Jacques,1895-05-11,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,Grande,NaN,1930-07-25,Albert,1878-04-17,1878.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,Average,61.0,NaN,Polina,2002-01-30,2002.0
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,Average,65.0,NaN,Valeriya,1999-09-20,1999.0
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,Short,55.0,NaN,Yuliya,1998-05-08,1998.0
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,Average,NaN,1986-03-18,André,1899-05-19,1899.0
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,Grande,NaN,2003-10-20,Bill,1913-07-15,1913.0

In [ ]:


bios_new['year']= bios_new['born_datenew'].dt.year
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datenew,year
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,Grande,NaN,1960-10-02,Jean-François,1886-12-12,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,Average,76.0,NaN,Arnaud,1969-04-01,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,Average,76.0,1994-07-17,Jean,1898-08-13,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,Average,64.0,1978-03-20,Jacques,1895-05-11,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,Grande,NaN,1930-07-25,Albert,1878-04-17,1878.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,Average,61.0,NaN,Polina,2002-01-30,2002.0
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,Average,65.0,NaN,Valeriya,1999-09-20,1999.0
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,Short,55.0,NaN,Yuliya,1998-05-08,1998.0
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,Average,NaN,1986-03-18,André,1899-05-19,1899.0
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,Grande,NaN,2003-10-20,Bill,1913-07-15,1913.0

In [266]:
submit=bios_new[['athlete_id','year']]
submit.to_csv('./data/submit_csv', index=False)

In [270]:
df['height_category'] = df['height_cm'].apply(lambda x: 'Short' if x <165 else ('middle'if x <185 else 'Tall'))
df

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,middle
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,middle
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,middle
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,middle
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,middle
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Short
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,middle
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Tall

In [274]:
def categorize_athlete(row):
    if (row['height_cm'] <175) & (row['weight_kg']<70):
        return 'LightWeight'
    if row['height_cm'] <185 and row['weight_kg']<85:
        return 'MiddleWeight'
    else:
        return 'HeavyWeight'

df['Category']=df.apply(categorize_athlete,axis=1)

In [275]:
df

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,HeavyWeight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,middle,MiddleWeight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,middle,MiddleWeight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,middle,LightWeight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,HeavyWeight
...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,middle,LightWeight
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,middle,LightWeight
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Short,LightWeight
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,middle,HeavyWeight
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Tall,HeavyWeight

In [276]:
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,Grande,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,Average,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,Average,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,Average,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,Grande,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,Average,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,Average,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,Short,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,Average,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,Grande,NaN,2003-10-20

In [277]:
bios=pd.read_excel('./data/olympics.xlsx')

In [278]:
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [280]:
noc= pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/noc_regions.csv')
noc

     NOC       region                 notes
0    AFG  Afghanistan                   NaN
1    AHO      Curacao  Netherlands Antilles
2    ALB      Albania                   NaN
3    ALG      Algeria                   NaN
4    AND      Andorra                   NaN
..   ...          ...                   ...
225  YEM        Yemen                   NaN
226  YMD        Yemen           South Yemen
227  YUG       Serbia            Yugoslavia
228  ZAM       Zambia                   NaN
229  ZIM     Zimbabwe                   NaN

[230 rows x 3 columns]

In [281]:
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [289]:
bios_new=pd.merge(bios,noc, left_on='born_country', right_on='NOC', how='left')

In [288]:
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [292]:
bios_new.rename(columns={'region':'born_country_full' }, inplace=True)

In [293]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,born_country_full,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,RUS,Russia,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,RUS,Russia,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,RUS,Russia,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,FRA,France,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,AUS,Australia,NaN

In [294]:
bios_new[bios_new['NOC_x'] != bios_new['born_country_full']] [['name','NOC_x','born_country_full']]

                       name    NOC_x born_country_full
4              Albert Canet   France                UK
12                J. Defert   France               NaN
13           Étienne Durand   France               NaN
16               Guy Forget   France           Morocco
27       Guy, Baron Lejeune   France               NaN
...                     ...      ...               ...
145491        Matthew Wepke  Jamaica               NaN
145493   Landysh Falyakhova      ROC            Russia
145495    Polina Luchnikova      ROC            Russia
145496  Valeriya Merkusheva      ROC            Russia
145497      Yuliya Smirnova      ROC            Russia

[73210 rows x 3 columns]

In [297]:
usa= bios[bios['born_country']=='USA'].copy()
gbr= bios[bios['born_country']=='GBR'].copy()

In [298]:
pd.concat([usa,gbr])

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...
144811,148512,Benjamin Alexander,1983-05-08,London,England,GBR,Jamaica,NaN,NaN,NaN
144815,148517,Ashley Watson,1993-10-28,Peterborough,England,GBR,Jamaica,NaN,NaN,NaN
145005,148716,Peder Kongshaug,2001-08-13,Wimbledon,England,GBR,Norway,184.0,86.0,NaN
145319,149041,Axel Brown,1992-04-02,Harrogate,England,GBR,Trinidad and Tobago,NaN,NaN,NaN
145388,149111,Jean-Luc Baker,1993-10-07,Burnley,England,GBR,United States,NaN,NaN,NaN

In [303]:
import numpy as np
coffee.iloc[2:4, 2]= np.nan

In [317]:
coffee['Units Sold']=coffee['Units Sold'].interpolate()
coffee

          Day Coffee Type  Units Sold  new_price  revenue
0      Monday    Espresso        25.0       5.99   149.75
1      Monday       Latte        15.0       5.99    89.85
2     Tuesday    Espresso        20.0       5.99   179.70
3     Tuesday       Latte        25.0       5.99   119.80
4   Wednesday    Espresso        30.0       5.99   179.70
5   Wednesday       Latte        25.0       5.99   149.75
6    Thursday    Espresso        30.0       5.99   179.70
7    Thursday       Latte        30.0       5.99   179.70
8      Friday    Espresso        45.0       5.99   269.55
9      Friday       Latte        35.0       5.99   209.65
10   Saturday    Espresso        45.0       5.99   269.55
11   Saturday       Latte        35.0       5.99   209.65
12     Sunday    Espresso        45.0       5.99   269.55
13     Sunday       Latte        35.0       5.99   209.65

In [318]:
import numpy as np
coffee.iloc[2:4, 2]= np.nan
coffee

          Day Coffee Type  Units Sold  new_price  revenue
0      Monday    Espresso        25.0       5.99   149.75
1      Monday       Latte        15.0       5.99    89.85
2     Tuesday    Espresso         NaN       5.99   179.70
3     Tuesday       Latte         NaN       5.99   119.80
4   Wednesday    Espresso        30.0       5.99   179.70
5   Wednesday       Latte        25.0       5.99   149.75
6    Thursday    Espresso        30.0       5.99   179.70
7    Thursday       Latte        30.0       5.99   179.70
8      Friday    Espresso        45.0       5.99   269.55
9      Friday       Latte        35.0       5.99   209.65
10   Saturday    Espresso        45.0       5.99   269.55
11   Saturday       Latte        35.0       5.99   209.65
12     Sunday    Espresso        45.0       5.99   269.55
13     Sunday       Latte        35.0       5.99   209.65

In [ ]:
coffee[coffee['Units Sold'].notna()] #isna() nanları getirir notna nan olmayanları

          Day Coffee Type  Units Sold  new_price  revenue
0      Monday    Espresso        25.0       5.99   149.75
1      Monday       Latte        15.0       5.99    89.85
4   Wednesday    Espresso        30.0       5.99   179.70
5   Wednesday       Latte        25.0       5.99   149.75
6    Thursday    Espresso        30.0       5.99   179.70
7    Thursday       Latte        30.0       5.99   179.70
8      Friday    Espresso        45.0       5.99   269.55
9      Friday       Latte        35.0       5.99   209.65
10   Saturday    Espresso        45.0       5.99   269.55
11   Saturday       Latte        35.0       5.99   209.65
12     Sunday    Espresso        45.0       5.99   269.55
13     Sunday       Latte        35.0       5.99   209.65

In [322]:
bios['born_city'].value_counts()

born_city
Budapest            1378
Moskva (Moscow)      883
Oslo                 708
Stockholm            629
Praha (Prague)       600
                    ...
Tsivilsk               1
Roth                   1
Romoos                 1
Dva Polya Artash       1
Dulwich Hill           1
Name: count, Length: 22368, dtype: int64

In [323]:
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [324]:
bios[bios['born_country']=='USA']['born_region'].value_counts()

born_region
California              1634
New York                 990
Illinois                 585
Pennsylvania             530
Massachusetts            530
New Jersey               381
Texas                    368
Minnesota                365
Ohio                     328
Michigan                 319
Washington               240
Florida                  235
Wisconsin                209
Colorado                 207
Connecticut              156
Indiana                  150
Oregon                   132
Georgia                  129
Virginia                 121
Maryland                 117
District of Columbia     107
Iowa                     102
Hawaiʻi                   95
Kansas                    94
Oklahoma                  93
Louisiana                 92
Utah                      91
Missouri                  91
North Carolina            86
Arizona                   83
New Hampshire             83
Vermont                   68
Mississippi               66
Alabama                   64
Tennessee                 62
Kentucky                  62
Nebraska                  60
Rhode Island              56
Montana                   55
Maine                     50
South Carolina            50
Alaska                    45
Arkansas                  42
Idaho                     41
New Mexico                38
Nevada                    36
South Dakota              27
West Virginia             24
Delaware                  22
North Dakota              16
Wyoming                   14
Name: count, dtype: int64

In [327]:
coffee['Units Sold'] = coffee['Units Sold'].interpolate()
coffee

          Day Coffee Type  Units Sold  new_price  revenue
0      Monday    Espresso        25.0       5.99   149.75
1      Monday       Latte        15.0       5.99    89.85
2     Tuesday    Espresso        20.0       5.99   179.70
3     Tuesday       Latte        25.0       5.99   119.80
4   Wednesday    Espresso        30.0       5.99   179.70
5   Wednesday       Latte        25.0       5.99   149.75
6    Thursday    Espresso        30.0       5.99   179.70
7    Thursday       Latte        30.0       5.99   179.70
8      Friday    Espresso        45.0       5.99   269.55
9      Friday       Latte        35.0       5.99   209.65
10   Saturday    Espresso        45.0       5.99   269.55
11   Saturday       Latte        35.0       5.99   209.65
12     Sunday    Espresso        45.0       5.99   269.55
13     Sunday       Latte        35.0       5.99   209.65

In [ ]:
coffee.groupby('Coffee Type')['revenue'].sum()

Coffee Type
Espresso    1497.50
Latte       1168.05
Name: revenue, dtype: float64

In [334]:
coffee.groupby('Coffee Type').agg({'Units Sold':'mean', 'revenue':'sum'})

             Units Sold  revenue
Coffee Type
Espresso      34.285714  1497.50
Latte         28.571429  1168.05

In [336]:
pivot=coffee.pivot(columns='Coffee Type', index='Day',values='revenue')
pivot

Coffee Type  Espresso   Latte
Day
Friday         269.55  209.65
Monday         149.75   89.85
Saturday       269.55  209.65
Sunday         269.55  209.65
Thursday       179.70  179.70
Tuesday        179.70  119.80
Wednesday      179.70  149.75

In [342]:
bios['born_date']=pd.to_datetime(bios['born_date'])
bios.groupby(bios['born_date'].dt.year)['name'].count()

born_date
1828.0      1
1831.0      2
1833.0      1
1836.0      1
1837.0      1
         ...
2005.0    163
2006.0     17
2007.0      3
2008.0      3
2009.0      1
Name: name, Length: 177, dtype: int64

In [ ]:
coffee['yesterday_revenue']=coffee['revenue'].shift(2)
coffee['ratio']=(
coffee

          Day Coffee Type  Units Sold  new_price  revenue  yesterday_revenue
0      Monday    Espresso        25.0       5.99   149.75                NaN
1      Monday       Latte        15.0       5.99    89.85                NaN
2     Tuesday    Espresso        20.0       5.99   179.70             149.75
3     Tuesday       Latte        25.0       5.99   119.80              89.85
4   Wednesday    Espresso        30.0       5.99   179.70             179.70
5   Wednesday       Latte        25.0       5.99   149.75             119.80
6    Thursday    Espresso        30.0       5.99   179.70             179.70
7    Thursday       Latte        30.0       5.99   179.70             149.75
8      Friday    Espresso        45.0       5.99   269.55             179.70
9      Friday       Latte        35.0       5.99   209.65             179.70
10   Saturday    Espresso        45.0       5.99   269.55             269.55
11   Saturday       Latte        35.0       5.99   209.65             209.65
12     Sunday    Espresso        45.0       5.99   269.55             269.55
13     Sunday       Latte        35.0       5.99   209.65             209.65