In [ ]:
# prıncıpal component analysis
""""




PCA (Temel Bileşenler Analizi), büyük ve karmaşık veri setlerini, 
içindeki önemli bilgiyi kaybetmeden daha küçük ve yönetilebilir 
parçalara indirmemizi sağlayan bir boyut indirgeme (dimension reduction) tekniğidir.

Şöyle düşünebilirsin: Elinde bir nesnenin 100 farklı açıdan çekilmiş 
fotoğrafı var. PCA, bu 100 fotoğrafa bakıp "Aslında bu nesnenin 
şeklini anlamak için şu 3 ana açı yeterli, diğerleri sadece detay 
veya gürültü" der.

İşin teknik mutfağında dönen olaylar ise özetle şunlar:

1. Temel Mantık: Varyans
PCA'nın ana hedefi, verideki varyansı (değişkenliği) maksimize
etmektir. Verinin en çok "dağıldığı" yönleri bulur. Çünkü bir 
verideki en büyük değişkenlik, genellikle o verinin taşıdığı en 
değerli bilgidir.
"""

In [1]:
import pandas as pd 
import numpy as np

In [52]:
import pandas as pd

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# load dataset into Pandas DataFrame
df = pd.read_csv(url, names=['sepal length','sepal width','petal length','petal width','target'])

In [53]:
df.head()

   sepal length  sepal width  petal length  petal width       target
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
features=['sepal length','sepal width','petal length','petal width']
X=df.loc[:,features].values
y=df.loc[:,['target']].values

X.head()

   sepal length  sepal width  petal length  petal width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [63]:
X= scaler.fit_transform(X)
X=pd.DataFrame(X, columns=['sepal length','sepal width','petal length','petal width'])
X.head()

   sepal length  sepal width  petal length  petal width
0     -0.900681     1.032057     -1.341272    -1.312977
1     -1.143017    -0.124958     -1.341272    -1.312977
2     -1.385353     0.337848     -1.398138    -1.312977
3     -1.506521     0.106445     -1.284407    -1.312977
4     -1.021849     1.263460     -1.341272    -1.312977