In [1]:
import seaborn as sns 
import pandas as pd

df=sns.load_dataset('healthexp')
df.head(10)

   Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9
3  1970          Japan       150.437             72.0
4  1970            USA       326.961             70.9
5  1971         Canada       313.391             72.8
6  1971        Germany       298.251             70.8
7  1971  Great Britain       134.172             71.9
8  1971          Japan       163.854             72.9
9  1971            USA       357.988             71.2

In [2]:
df=pd.get_dummies(data=df)
df.head()

,Year,Spending_USD,Life_Expectancy,Country_Canada,Country_France,Country_Germany,Country_Great Britain,Country_Japan,Country_USA
0,1970,252.311,70.6,False,False,True,False,False,False
1,1970,192.143,72.2,False,True,False,False,False,False
2,1970,123.993,71.9,False,False,False,True,False,False
3,1970,150.437,72.0,False,False,False,False,True,False
4,1970,326.961,70.9,False,False,False,False,False,True

In [3]:
X=df.drop(columns=['Life_Expectancy'])
y=df['Life_Expectancy']

In [5]:
from sklearn.model_selection import train_test_split
X_Train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.8,random_state=54)

In [6]:
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor(random_state=34)

In [7]:
rfr.fit(X_Train,y_train)

RandomForestRegressor(random_state=34)

In [8]:
y_pred=rfr.predict(X_test)

In [9]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [10]:
mean_absolute_error(y_test,y_pred)

0.31138181818180044

In [11]:
mean_squared_error(y_pred,y_test)

0.1553235999999905

In [12]:
r2_score(y_test,y_pred)

0.9836234548107303

In [16]:
pip install optuna

Collecting optuna
  Using cached optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
Collecting alembic>=1.5.0 (from optuna)
  Using cached alembic-1.18.4-py3-none-any.whl.metadata (7.2 kB)
Collecting colorlog (from optuna)
  Using cached colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in c:\users\computeer\appdata\local\programs\python\python313\lib\site-packages (from optuna) (2.4.2)
Requirement already satisfied: packaging>=20.0 in c:\users\computeer\appdata\roaming\python\python313\site-packages (from optuna) (26.0)
Collecting sqlalchemy>=1.4.2 (from optuna)
  Downloading sqlalchemy-2.0.49-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: tqdm in c:\users\computeer\appdata\local\programs\python\python313\lib\site-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in c:\users\computeer\appdata\local\programs\python\python313\lib\site-packages (from optuna) (6.0.3)
Collecting Mako (from alembic>=1.5.0->optuna)
  Using cached mako-1.3.12-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4.12 in c:\users\computeer\appdata\local\programs\python\python313\lib\site-packages (from alembic>=1.5.0->optuna) (4.15.0)
Collecting greenlet>=1 (from sqlalchemy>=1.4.2->optuna)
  Downloading greenlet-3.5.0-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: colorama in c:\users\computeer\appdata\roaming\python\python313\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\computeer\appdata\local\programs\python\python313\lib\site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Using cached optuna-4.8.0-py3-none-any.whl (419 kB)
Using cached alembic-1.18.4-py3-none-any.whl (263 kB)
Downloading sqlalchemy-2.0.49-cp313-cp313-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 33.8 MB/s eta 0:00:00
Using cached colorlog-6.10.1-py3-none-any.whl (11 kB)
Downloading greenlet-3.5.0-cp313-cp313-win_amd64.whl (238 kB)
Using cached mako-1.3.12-py3-none-any.whl (78 kB)
Installing collected packages: Mako, greenlet, colorlog, sqlalchemy, alembic, optuna
Successfully installed Mako-1.3.12 alembic-1.18.4 colorlog-6.10.1 greenlet-3.5.0 optuna-4.8.0 sqlalchemy-2.0.49
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [17]:
import optuna

In [22]:
from sklearn.model_selection import cross_val_score

In [26]:
def objective(trial):
    n_estimators= trial.suggest_int('n_estimators',100,1000)
    max_depth=trial.suggest_int('max_depth',10,50)
    min_samples_split=trial.suggest_int('min_samples_split',2,32)
    min_samples_leaf=trial.suggest_int('min_samples_leaf',1,32)
    
    model=RandomForestRegressor(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
    )
    
    score=cross_val_score(model,X_Train,y_train, cv=5,scoring='neg_mean_squared_error',n_jobs=-1).mean()
    return score

In [27]:
study=optuna.create_study(direction='maximize',sampler=optuna.samplers.RandomSampler(seed=42))

[I 2026-05-05 20:03:06,454] A new study created in memory with name: no-name-105b6eb2-bd64-4c34-a12c-8e4390960969

In [28]:
study.optimize(objective,n_trials=200)

[I 2026-05-05 20:03:14,628] Trial 0 finished with value: -2.3072194221617885 and parameters: {'n_estimators': 437, 'max_depth': 48, 'min_samples_split': 24, 'min_samples_leaf': 20}. Best is trial 0 with value: -2.3072194221617885.
[I 2026-05-05 20:03:19,091] Trial 1 finished with value: -2.9031479297681897 and parameters: {'n_estimators': 240, 'max_depth': 16, 'min_samples_split': 3, 'min_samples_leaf': 28}. Best is trial 0 with value: -2.3072194221617885.
[I 2026-05-05 20:03:23,204] Trial 2 finished with value: -3.34043601971631 and parameters: {'n_estimators': 641, 'max_depth': 39, 'min_samples_split': 2, 'min_samples_leaf': 32}. Best is trial 0 with value: -2.3072194221617885.
[I 2026-05-05 20:03:24,629] Trial 3 finished with value: -1.0083653770417778 and parameters: {'n_estimators': 850, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 6}. Best is trial 3 with value: -1.0083653770417778.
[I 2026-05-05 20:03:25,185] Trial 4 finished with value: -1.5615423402515018 and parameters: {'n_estimators': 374, 'max_depth': 31, 'min_samples_split': 15, 'min_samples_leaf': 10}. Best is trial 3 with value: -1.0083653770417778.
[I 2026-05-05 20:03:26,160] Trial 5 finished with value: -1.7787617771463384 and parameters: {'n_estimators': 651, 'max_depth': 15, 'min_samples_split': 11, 'min_samples_leaf': 12}. Best is trial 3 with value: -1.0083653770417778.
[I 2026-05-05 20:03:26,930] Trial 6 finished with value: -2.188957250953307 and parameters: {'n_estimators': 510, 'max_depth': 42, 'min_samples_split': 8, 'min_samples_leaf': 17}. Best is trial 3 with value: -1.0083653770417778.
[I 2026-05-05 20:03:27,866] Trial 7 finished with value: -1.1171777215089826 and parameters: {'n_estimators': 633, 'max_depth': 11, 'min_samples_split': 20, 'min_samples_leaf': 6}. Best is trial 3 with value: -1.0083653770417778.
[I 2026-05-05 20:03:28,110] Trial 8 finished with value: -2.6883134271401516 and parameters: {'n_estimators': 158, 'max_depth': 48, 'min_samples_split': 31, 'min_samples_leaf': 26}. Best is trial 3 with value: -1.0083653770417778.
[I 2026-05-05 20:03:28,659] Trial 9 finished with value: -2.076962075628727 and parameters: {'n_estimators': 374, 'max_depth': 14, 'min_samples_split': 23, 'min_samples_leaf': 15}. Best is trial 3 with value: -1.0083653770417778.
[I 2026-05-05 20:03:28,992] Trial 10 finished with value: -3.116698589437815 and parameters: {'n_estimators': 209, 'max_depth': 30, 'min_samples_split': 3, 'min_samples_leaf': 30}. Best is trial 3 with value: -1.0083653770417778.
[I 2026-05-05 20:03:29,544] Trial 11 finished with value: -2.182227674095188 and parameters: {'n_estimators': 333, 'max_depth': 37, 'min_samples_split': 11, 'min_samples_leaf': 17}. Best is trial 3 with value: -1.0083653770417778.
[I 2026-05-05 20:03:30,443] Trial 12 finished with value: -2.584545609065986 and parameters: {'n_estimators': 592, 'max_depth': 17, 'min_samples_split': 32, 'min_samples_leaf': 25}. Best is trial 3 with value: -1.0083653770417778.
[I 2026-05-05 20:03:31,724] Trial 13 finished with value: -3.1339147590628396 and parameters: {'n_estimators': 946, 'max_depth': 46, 'min_samples_split': 20, 'min_samples_leaf': 30}. Best is trial 3 with value: -1.0083653770417778.
[I 2026-05-05 20:03:32,010] Trial 14 finished with value: -1.6778563950499579 and parameters: {'n_estimators': 179, 'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 11}. Best is trial 3 with value: -1.0083653770417778.
[I 2026-05-05 20:03:32,663] Trial 15 finished with value: -1.8352754631255082 and parameters: {'n_estimators': 450, 'max_depth': 21, 'min_samples_split': 27, 'min_samples_leaf': 12}. Best is trial 3 with value: -1.0083653770417778.
[I 2026-05-05 20:03:33,189] Trial 16 finished with value: -2.683718362811707 and parameters: {'n_estimators': 353, 'max_depth': 32, 'min_samples_split': 6, 'min_samples_leaf': 26}. Best is trial 3 with value: -1.0083653770417778.
[I 2026-05-05 20:03:33,465] Trial 17 finished with value: -1.3685735813073696 and parameters: {'n_estimators': 167, 'max_depth': 50, 'min_samples_split': 25, 'min_samples_leaf': 7}. Best is trial 3 with value: -1.0083653770417778.
[I 2026-05-05 20:03:33,633] Trial 18 finished with value: -2.493799603067955 and parameters: {'n_estimators': 104, 'max_depth': 43, 'min_samples_split': 23, 'min_samples_leaf': 24}. Best is trial 3 with value: -1.0083653770417778.
[I 2026-05-05 20:03:34,961] Trial 19 finished with value: -0.6598766446621787 and parameters: {'n_estimators': 794, 'max_depth': 13, 'min_samples_split': 13, 'min_samples_leaf': 4}. Best is trial 19 with value: -0.6598766446621787.
[I 2026-05-05 20:03:36,269] Trial 20 finished with value: -0.5239159718446803 and parameters: {'n_estimators': 877, 'max_depth': 35, 'min_samples_split': 12, 'min_samples_leaf': 3}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:36,826] Trial 21 finished with value: -2.359782280925709 and parameters: {'n_estimators': 380, 'max_depth': 23, 'min_samples_split': 24, 'min_samples_leaf': 21}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:38,119] Trial 22 finished with value: -2.4462335878145396 and parameters: {'n_estimators': 899, 'max_depth': 29, 'min_samples_split': 5, 'min_samples_leaf': 23}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:39,280] Trial 23 finished with value: -2.1422565432728717 and parameters: {'n_estimators': 785, 'max_depth': 33, 'min_samples_split': 25, 'min_samples_leaf': 16}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:40,132] Trial 24 finished with value: -0.5725293180744467 and parameters: {'n_estimators': 570, 'max_depth': 27, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:40,321] Trial 25 finished with value: -2.184415736193736 and parameters: {'n_estimators': 128, 'max_depth': 36, 'min_samples_split': 11, 'min_samples_leaf': 17}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:41,607] Trial 26 finished with value: -2.5876823402359035 and parameters: {'n_estimators': 917, 'max_depth': 20, 'min_samples_split': 14, 'min_samples_leaf': 25}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:42,164] Trial 27 finished with value: -1.018816719538647 and parameters: {'n_estimators': 306, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 6}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:43,522] Trial 28 finished with value: -2.8943997677575823 and parameters: {'n_estimators': 937, 'max_depth': 43, 'min_samples_split': 21, 'min_samples_leaf': 28}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:44,646] Trial 29 finished with value: -2.2357553142340914 and parameters: {'n_estimators': 824, 'max_depth': 17, 'min_samples_split': 29, 'min_samples_leaf': 18}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:45,809] Trial 30 finished with value: -0.6210069160223288 and parameters: {'n_estimators': 827, 'max_depth': 46, 'min_samples_split': 11, 'min_samples_leaf': 4}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:46,249] Trial 31 finished with value: -2.8926227622897556 and parameters: {'n_estimators': 305, 'max_depth': 27, 'min_samples_split': 27, 'min_samples_leaf': 28}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:46,427] Trial 32 finished with value: -1.3528044946102806 and parameters: {'n_estimators': 106, 'max_depth': 30, 'min_samples_split': 14, 'min_samples_leaf': 8}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:46,758] Trial 33 finished with value: -1.827054466335659 and parameters: {'n_estimators': 207, 'max_depth': 23, 'min_samples_split': 31, 'min_samples_leaf': 11}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:47,542] Trial 34 finished with value: -3.338276984155331 and parameters: {'n_estimators': 567, 'max_depth': 38, 'min_samples_split': 13, 'min_samples_leaf': 32}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:49,129] Trial 35 finished with value: -1.5716972023000029 and parameters: {'n_estimators': 967, 'max_depth': 20, 'min_samples_split': 17, 'min_samples_leaf': 10}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:49,624] Trial 36 finished with value: -2.1921175432707343 and parameters: {'n_estimators': 356, 'max_depth': 11, 'min_samples_split': 20, 'min_samples_leaf': 17}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:49,836] Trial 37 finished with value: -1.5866459923281626 and parameters: {'n_estimators': 146, 'max_depth': 21, 'min_samples_split': 30, 'min_samples_leaf': 8}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:50,218] Trial 38 finished with value: -1.6391120420421863 and parameters: {'n_estimators': 230, 'max_depth': 30, 'min_samples_split': 32, 'min_samples_leaf': 8}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:51,244] Trial 39 finished with value: -2.523776784674328 and parameters: {'n_estimators': 705, 'max_depth': 41, 'min_samples_split': 9, 'min_samples_leaf': 24}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:51,836] Trial 40 finished with value: -2.2485272338875992 and parameters: {'n_estimators': 431, 'max_depth': 35, 'min_samples_split': 21, 'min_samples_leaf': 18}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:52,143] Trial 41 finished with value: -1.0280360587737774 and parameters: {'n_estimators': 181, 'max_depth': 44, 'min_samples_split': 11, 'min_samples_leaf': 6}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:52,378] Trial 42 finished with value: -0.9691911423027555 and parameters: {'n_estimators': 136, 'max_depth': 34, 'min_samples_split': 23, 'min_samples_leaf': 1}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:53,206] Trial 43 finished with value: -1.1672766796295586 and parameters: {'n_estimators': 561, 'max_depth': 19, 'min_samples_split': 22, 'min_samples_leaf': 6}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:54,250] Trial 44 finished with value: -1.4236229804460807 and parameters: {'n_estimators': 722, 'max_depth': 25, 'min_samples_split': 31, 'min_samples_leaf': 5}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:54,821] Trial 45 finished with value: -3.0170434417193426 and parameters: {'n_estimators': 407, 'max_depth': 14, 'min_samples_split': 30, 'min_samples_leaf': 29}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:55,326] Trial 46 finished with value: -2.2341082903348677 and parameters: {'n_estimators': 332, 'max_depth': 37, 'min_samples_split': 27, 'min_samples_leaf': 18}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:56,133] Trial 47 finished with value: -3.0128196874636384 and parameters: {'n_estimators': 577, 'max_depth': 19, 'min_samples_split': 4, 'min_samples_leaf': 29}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:57,461] Trial 48 finished with value: -1.796891690379661 and parameters: {'n_estimators': 911, 'max_depth': 35, 'min_samples_split': 12, 'min_samples_leaf': 12}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:58,531] Trial 49 finished with value: -2.5780904516292495 and parameters: {'n_estimators': 754, 'max_depth': 46, 'min_samples_split': 29, 'min_samples_leaf': 25}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:03:59,448] Trial 50 finished with value: -3.044109060823282 and parameters: {'n_estimators': 678, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 29}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:04:00,333] Trial 51 finished with value: -2.406291083787777 and parameters: {'n_estimators': 646, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 22}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:04:00,491] Trial 52 finished with value: -2.479838788985392 and parameters: {'n_estimators': 104, 'max_depth': 16, 'min_samples_split': 19, 'min_samples_leaf': 23}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:04:01,481] Trial 53 finished with value: -1.458242574336269 and parameters: {'n_estimators': 687, 'max_depth': 19, 'min_samples_split': 24, 'min_samples_leaf': 8}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:04:02,019] Trial 54 finished with value: -2.904475034375764 and parameters: {'n_estimators': 393, 'max_depth': 40, 'min_samples_split': 22, 'min_samples_leaf': 28}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:04:03,022] Trial 55 finished with value: -1.8005344530604455 and parameters: {'n_estimators': 692, 'max_depth': 33, 'min_samples_split': 4, 'min_samples_leaf': 12}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:04:03,516] Trial 56 finished with value: -1.956290422872102 and parameters: {'n_estimators': 338, 'max_depth': 20, 'min_samples_split': 32, 'min_samples_leaf': 13}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:04:04,846] Trial 57 finished with value: -2.18847130584661 and parameters: {'n_estimators': 903, 'max_depth': 35, 'min_samples_split': 26, 'min_samples_leaf': 17}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:04:05,819] Trial 58 finished with value: -2.502538329755464 and parameters: {'n_estimators': 619, 'max_depth': 30, 'min_samples_split': 8, 'min_samples_leaf': 24}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:04:06,338] Trial 59 finished with value: -1.1805050558466477 and parameters: {'n_estimators': 352, 'max_depth': 10, 'min_samples_split': 22, 'min_samples_leaf': 6}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:04:07,664] Trial 60 finished with value: -1.8763651845010578 and parameters: {'n_estimators': 947, 'max_depth': 49, 'min_samples_split': 30, 'min_samples_leaf': 12}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:04:07,833] Trial 61 finished with value: -3.260968701447736 and parameters: {'n_estimators': 113, 'max_depth': 48, 'min_samples_split': 15, 'min_samples_leaf': 31}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:04:09,232] Trial 62 finished with value: -1.9018460665093222 and parameters: {'n_estimators': 968, 'max_depth': 44, 'min_samples_split': 11, 'min_samples_leaf': 13}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:04:10,402] Trial 63 finished with value: -2.223192652528266 and parameters: {'n_estimators': 866, 'max_depth': 22, 'min_samples_split': 7, 'min_samples_leaf': 18}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:04:11,731] Trial 64 finished with value: -0.8401654111829504 and parameters: {'n_estimators': 943, 'max_depth': 38, 'min_samples_split': 19, 'min_samples_leaf': 4}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:04:12,688] Trial 65 finished with value: -2.187325210456301 and parameters: {'n_estimators': 654, 'max_depth': 50, 'min_samples_split': 6, 'min_samples_leaf': 17}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:04:13,963] Trial 66 finished with value: -2.436566560697945 and parameters: {'n_estimators': 890, 'max_depth': 40, 'min_samples_split': 23, 'min_samples_leaf': 23}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:04:14,585] Trial 67 finished with value: -2.6965001506339528 and parameters: {'n_estimators': 423, 'max_depth': 22, 'min_samples_split': 27, 'min_samples_leaf': 26}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:04:15,785] Trial 68 finished with value: -2.189824222559378 and parameters: {'n_estimators': 881, 'max_depth': 47, 'min_samples_split': 17, 'min_samples_leaf': 17}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:04:17,044] Trial 69 finished with value: -2.6851202325568613 and parameters: {'n_estimators': 819, 'max_depth': 36, 'min_samples_split': 23, 'min_samples_leaf': 26}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:04:18,337] Trial 70 finished with value: -0.666537784262792 and parameters: {'n_estimators': 901, 'max_depth': 23, 'min_samples_split': 13, 'min_samples_leaf': 4}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:04:19,231] Trial 71 finished with value: -2.2360844549803156 and parameters: {'n_estimators': 621, 'max_depth': 11, 'min_samples_split': 16, 'min_samples_leaf': 18}. Best is trial 20 with value: -0.5239159718446803.
[I 2026-05-05 20:04:19,852] Trial 72 finished with value: -0.27497691778592454 and parameters: {'n_estimators': 358, 'max_depth': 34, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 72 with value: -0.27497691778592454.
[I 2026-05-05 20:04:21,031] Trial 73 finished with value: -2.1743184927893937 and parameters: {'n_estimators': 841, 'max_depth': 24, 'min_samples_split': 5, 'min_samples_leaf': 17}. Best is trial 72 with value: -0.27497691778592454.
[I 2026-05-05 20:04:22,173] Trial 74 finished with value: -0.8629440316225654 and parameters: {'n_estimators': 793, 'max_depth': 18, 'min_samples_split': 21, 'min_samples_leaf': 3}. Best is trial 72 with value: -0.27497691778592454.
[I 2026-05-05 20:04:22,397] Trial 75 finished with value: -2.352121494766986 and parameters: {'n_estimators': 146, 'max_depth': 31, 'min_samples_split': 18, 'min_samples_leaf': 21}. Best is trial 72 with value: -0.27497691778592454.
[I 2026-05-05 20:04:23,469] Trial 76 finished with value: -1.6860226807044547 and parameters: {'n_estimators': 754, 'max_depth': 50, 'min_samples_split': 18, 'min_samples_leaf': 11}. Best is trial 72 with value: -0.27497691778592454.
[I 2026-05-05 20:04:24,861] Trial 77 finished with value: -0.61540971508612 and parameters: {'n_estimators': 816, 'max_depth': 21, 'min_samples_split': 15, 'min_samples_leaf': 3}. Best is trial 72 with value: -0.27497691778592454.
[I 2026-05-05 20:04:25,049] Trial 78 finished with value: -2.492550954914166 and parameters: {'n_estimators': 122, 'max_depth': 49, 'min_samples_split': 27, 'min_samples_leaf': 23}. Best is trial 72 with value: -0.27497691778592454.
[I 2026-05-05 20:04:25,734] Trial 79 finished with value: -1.468919291042873 and parameters: {'n_estimators': 468, 'max_depth': 17, 'min_samples_split': 6, 'min_samples_leaf': 9}. Best is trial 72 with value: -0.27497691778592454.
[I 2026-05-05 20:04:26,629] Trial 80 finished with value: -1.523032626446433 and parameters: {'n_estimators': 594, 'max_depth': 39, 'min_samples_split': 22, 'min_samples_leaf': 9}. Best is trial 72 with value: -0.27497691778592454.
[I 2026-05-05 20:04:28,047] Trial 81 finished with value: -2.3118408660453884 and parameters: {'n_estimators': 960, 'max_depth': 40, 'min_samples_split': 19, 'min_samples_leaf': 20}. Best is trial 72 with value: -0.27497691778592454.
[I 2026-05-05 20:04:28,789] Trial 82 finished with value: -2.607242282864573 and parameters: {'n_estimators': 478, 'max_depth': 20, 'min_samples_split': 13, 'min_samples_leaf': 25}. Best is trial 72 with value: -0.27497691778592454.
[I 2026-05-05 20:04:29,012] Trial 83 finished with value: -0.2780170188370663 and parameters: {'n_estimators': 112, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 72 with value: -0.27497691778592454.
[I 2026-05-05 20:04:30,359] Trial 84 finished with value: -0.7406424947343584 and parameters: {'n_estimators': 870, 'max_depth': 38, 'min_samples_split': 16, 'min_samples_leaf': 4}. Best is trial 72 with value: -0.27497691778592454.
[I 2026-05-05 20:04:31,142] Trial 85 finished with value: -2.0188620459498727 and parameters: {'n_estimators': 542, 'max_depth': 29, 'min_samples_split': 7, 'min_samples_leaf': 14}. Best is trial 72 with value: -0.27497691778592454.

In [29]:
study.best_params

{'n_estimators': 940,
 'max_depth': 45,
 'min_samples_split': 3,
 'min_samples_leaf': 1}

In [30]:
best_params=study.best_params

In [31]:
import matplotlib.pyplot as plt

In [33]:
pip install nbformat

Collecting nbformat
  Downloading nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Collecting fastjsonschema>=2.15 (from nbformat)
  Downloading fastjsonschema-2.21.2-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: jsonschema>=2.6 in c:\users\computeer\appdata\local\programs\python\python313\lib\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\computeer\appdata\roaming\python\python313\site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\computeer\appdata\roaming\python\python313\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\computeer\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=2.6->nbformat) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\computeer\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\computeer\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\computeer\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\computeer\appdata\roaming\python\python313\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.9.2)
Downloading nbformat-5.10.4-py3-none-any.whl (78 kB)
Downloading fastjsonschema-2.21.2-py3-none-any.whl (24 kB)
Installing collected packages: fastjsonschema, nbformat
Successfully installed fastjsonschema-2.21.2 nbformat-5.10.4
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [34]:
optuna.visualization.plot_optimization_history(study)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'mode': 'markers',
              'name': 'Objective Value',
              'type': 'scatter',
              'x': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
                    18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
                    34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
                    50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
                    66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
                    82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
                    98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                    111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122,
                    123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134,
                    135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146,
                    147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158,
                    159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
                    171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
                    183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
                    195, 196, 197, 198, 199],
              'y': [-2.3072194221617885, -2.9031479297681897, -3.34043601971631,
                    -1.0083653770417778, -1.5615423402515018, -1.7787617771463384,
                    -2.188957250953307, -1.1171777215089826, -2.6883134271401516,
                    -2.076962075628727, -3.116698589437815, -2.182227674095188,
                    -2.584545609065986, -3.1339147590628396, -1.6778563950499579,
                    -1.8352754631255082, -2.683718362811707, -1.3685735813073696,
                    -2.493799603067955, -0.6598766446621787, -0.5239159718446803,
                    -2.359782280925709, -2.4462335878145396, -2.1422565432728717,
                    -0.5725293180744467, -2.184415736193736, -2.5876823402359035,
                    -1.018816719538647, -2.8943997677575823, -2.2357553142340914,
                    -0.6210069160223288, -2.8926227622897556, -1.3528044946102806,
                    -1.827054466335659, -3.338276984155331, -1.5716972023000029,
                    -2.1921175432707343, -1.5866459923281626, -1.6391120420421863,
                    -2.523776784674328, -2.2485272338875992, -1.0280360587737774,
                    -0.9691911423027555, -1.1672766796295586, -1.4236229804460807,
                    -3.0170434417193426, -2.2341082903348677, -3.0128196874636384,
                    -1.796891690379661, -2.5780904516292495, -3.044109060823282,
                    -2.406291083787777, -2.479838788985392, -1.458242574336269,
                    -2.904475034375764, -1.8005344530604455, -1.956290422872102,
                    -2.18847130584661, -2.502538329755464, -1.1805050558466477,
                    -1.8763651845010578, -3.260968701447736, -1.9018460665093222,
                    -2.223192652528266, -0.8401654111829504, -2.187325210456301,
                    -2.436566560697945, -2.6965001506339528, -2.189824222559378,
                    -2.6851202325568613, -0.666537784262792, -2.2360844549803156,
                    -0.27497691778592454, -2.1743184927893937, -0.8629440316225654,
                    -2.352121494766986, -1.6860226807044547, -0.61540971508612,
                    -2.492550954914166, -1.468919291042873, -1.523032626446433,
                    -2.3118408660453884, -2.607242282864573, -0.2780170188370663,
                    -0.7406424947343584, -2.0188620459498727, -0.8325836135200276,
                    -2.891613028556456, -2.3426585988376663, -2.2889449639023147,
                    -2.2308326808157477, -3.012144432306056, -0.2539030483895336,
                    -1.6738021359443653, -1.6768074221411653, -3.0115073902842435,
                    -1.0213387352550833, -2.0638766514303826, -3.1174212805530574,
                    -2.5987041143865013, -2.812716177130998, -0.5346056239435011,
                    -3.2298078935442156, -2.089263815115461, -2.6157854702954735,
                    -2.14544412744053, -2.9817096138127153, -2.5841540385451567,
                    -2.4553754523874716, -0.9614511167957108, -1.7885263615631435,
                    -2.5999574526580806, -2.2281982781343923, -2.157528414169483,
                    -0.5921925467307219, -2.2742835265871424, -2.9156291882005894,
                    -3.3624130571299347, -3.3649772609774855, -2.2105454193673566,
                    -2.35712639233573, -1.467927245084475, -2.303876848830907,
                    -1.8009736095081679, -3.320597303390881, -2.7839129792665673,
                    -2.8056591345372164, -2.0088322628824757, -0.2047760516554033,
                    -1.4551983766676884, -2.7779255406275523, -1.4553739687308591,
                    -3.3622392805896455, -3.2600014755362485, -0.8576168736085746,
                    -2.397979121157825, -2.3958442079597475, -2.9085882241445256,
                    -1.9508251205983502, -2.316692658530843, -0.2833591067348137,
                    -2.0126909196955, -2.664665720823435, -3.2409122748360772,
                    -1.4698545233999183, -1.695833023437001, -0.7955027376245363,
                    -2.3357478630299178, -2.166457446948672, -0.3347754997716007,
                    -0.4156859972970325, -1.8095616881647103, -2.6821978195553022,
                    -3.154673522026615, -2.561885570882366, -2.151435026028896,
                    -2.514537244264697, -2.9911248933702175, -2.0836654559139562,
                    -1.9091823621185067, -1.6522333991888314, -2.4038167322189645,
                    -2.2310578141268658, -0.8697680780219145, -2.2679067787989085,
                    -1.392472274101879, -1.0207503318898998, -3.028084367698452,
                    -3.3769629945593422, -2.9127581705276135, -2.4049492613829315,
                    -1.4689379579134014, -2.0070088818594627, -2.317963725892318,
                    -2.1371951456541165, -0.8179389697272669, -2.679910069683042,
                    -2.296674526691526, -3.1330145289245706, -2.505433292117909,
                    -2.5062318202986797, -2.6749069000854617, -2.7949547305322113,
                    -3.0255766190372055, -1.9088590609027953, -2.202776004701286,
                    -2.2329743017387167, -3.233541636956302, -2.689697847559102,
                    -2.6958428730715824, -2.502286808252186, -2.9845997523795385,
                    -2.9033585467762864, -1.1820338372239045, -2.349631316680705,
                    -1.8022472386086357, -1.9067423709311437, -2.263142639167328,
                    -2.8958219133541006, -3.125415929173472]},
             {'mode': 'lines',
              'name': 'Best Value',
              'type': 'scatter',
              'x': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
                    18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
                    34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
                    50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
                    66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
                    82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
                    98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                    111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122,
                    123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134,
                    135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146,
                    147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158,
                    159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
                    171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
                    183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
                    195, 196, 197, 198, 199],
              'y': [-2.3072194221617885, -2.3072194221617885, -2.3072194221617885,
                    -1.0083653770417778, -1.0083653770417778, -1.0083653770417778,
                    -1.0083653770417778, -1.0083653770417778, -1.0083653770417778,
                    -1.0083653770417778, -1.0083653770417778, -1.0083653770417778,
                    -1.0083653770417778, -1.0083653770417778, -1.0083653770417778,
                    -1.0083653770417778, -1.0083653770417778, -1.0083653770417778,
                    -1.0083653770417778, -0.6598766446621787, -0.5239159718446803,
                    -0.5239159718446803, -0.5239159718446803, -0.5239159718446803,
                    -0.5239159718446803, -0.5239159718446803, -0.5239159718446803,
                    -0.5239159718446803, -0.5239159718446803, -0.5239159718446803,
                    -0.5239159718446803, -0.5239159718446803, -0.5239159718446803,
                    -0.5239159718446803, -0.5239159718446803, -0.5239159718446803,
                    -0.5239159718446803, -0.5239159718446803, -0.5239159718446803,
                    -0.5239159718446803, -0.5239159718446803, -0.5239159718446803,
                    -0.5239159718446803, -0.5239159718446803, -0.5239159718446803,
                    -0.5239159718446803, -0.5239159718446803, -0.5239159718446803,
                    -0.5239159718446803, -0.5239159718446803, -0.5239159718446803,
                    -0.5239159718446803, -0.5239159718446803, -0.5239159718446803,
                    -0.5239159718446803, -0.5239159718446803, -0.5239159718446803,
                    -0.5239159718446803, -0.5239159718446803, -0.5239159718446803,
                    -0.5239159718446803, -0.5239159718446803, -0.5239159718446803,
                    -0.5239159718446803, -0.5239159718446803, -0.5239159718446803,
                    -0.5239159718446803, -0.5239159718446803, -0.5239159718446803,
                    -0.5239159718446803, -0.5239159718446803, -0.5239159718446803,
                    -0.27497691778592454, -0.27497691778592454,
                    -0.27497691778592454, -0.27497691778592454,
                    -0.27497691778592454, -0.27497691778592454,
                    -0.27497691778592454, -0.27497691778592454,
                    -0.27497691778592454, -0.27497691778592454,
                    -0.27497691778592454, -0.27497691778592454,
                    -0.27497691778592454, -0.27497691778592454,
                    -0.27497691778592454, -0.27497691778592454,
                    -0.27497691778592454, -0.27497691778592454,
                    -0.27497691778592454, -0.27497691778592454,
                    -0.2539030483895336, -0.2539030483895336, -0.2539030483895336,
                    -0.2539030483895336, -0.2539030483895336, -0.2539030483895336,
                    -0.2539030483895336, -0.2539030483895336, -0.2539030483895336,
                    -0.2539030483895336, -0.2539030483895336, -0.2539030483895336,
                    -0.2539030483895336, -0.2539030483895336, -0.2539030483895336,
                    -0.2539030483895336, -0.2539030483895336, -0.2539030483895336,
                    -0.2539030483895336, -0.2539030483895336, -0.2539030483895336,
                    -0.2539030483895336, -0.2539030483895336, -0.2539030483895336,
                    -0.2539030483895336, -0.2539030483895336, -0.2539030483895336,
                    -0.2539030483895336, -0.2539030483895336, -0.2539030483895336,
                    -0.2539030483895336, -0.2539030483895336, -0.2539030483895336,
                    -0.2539030483895336, -0.2539030483895336, -0.2539030483895336,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033,
                    -0.2047760516554033, -0.2047760516554033, -0.2047760516554033]},
             {'marker': {'color': '#cccccc'},
              'mode': 'markers',
              'name': 'Infeasible Trial',
              'showlegend': False,
              'type': 'scatter',
              'x': [],
              'y': []}],
    'layout': {'template': '...',
               'title': {'text': 'Optimization History Plot'},
               'xaxis': {'title': {'text': 'Trial'}},
               'yaxis': {'title': {'text': 'Objective Value'}}}
})

In [39]:

optuna.visualization.plot_parallel_coordinate(study)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'dimensions': [{'label': 'Objective Value',
                              'range': [-3.3769629945593422, -0.2047760516554033],
                              'values': [-2.3072194221617885, -2.9031479297681897,
                                         -3.34043601971631, -1.0083653770417778,
                                         -1.5615423402515018, -1.7787617771463384,
                                         -2.188957250953307, -1.1171777215089826,
                                         -2.6883134271401516, -2.076962075628727,
                                         -3.116698589437815, -2.182227674095188,
                                         -2.584545609065986, -3.1339147590628396,
                                         -1.6778563950499579, -1.8352754631255082,
                                         -2.683718362811707, -1.3685735813073696,
                                         -2.493799603067955, -0.6598766446621787,
                                         -0.5239159718446803, -2.359782280925709,
                                         -2.4462335878145396, -2.1422565432728717,
                                         -0.5725293180744467, -2.184415736193736,
                                         -2.5876823402359035, -1.018816719538647,
                                         -2.8943997677575823, -2.2357553142340914,
                                         -0.6210069160223288, -2.8926227622897556,
                                         -1.3528044946102806, -1.827054466335659,
                                         -3.338276984155331, -1.5716972023000029,
                                         -2.1921175432707343, -1.5866459923281626,
                                         -1.6391120420421863, -2.523776784674328,
                                         -2.2485272338875992, -1.0280360587737774,
                                         -0.9691911423027555, -1.1672766796295586,
                                         -1.4236229804460807, -3.0170434417193426,
                                         -2.2341082903348677, -3.0128196874636384,
                                         -1.796891690379661, -2.5780904516292495,
                                         -3.044109060823282, -2.406291083787777,
                                         -2.479838788985392, -1.458242574336269,
                                         -2.904475034375764, -1.8005344530604455,
                                         -1.956290422872102, -2.18847130584661,
                                         -2.502538329755464, -1.1805050558466477,
                                         -1.8763651845010578, -3.260968701447736,
                                         -1.9018460665093222, -2.223192652528266,
                                         -0.8401654111829504, -2.187325210456301,
                                         -2.436566560697945, -2.6965001506339528,
                                         -2.189824222559378, -2.6851202325568613,
                                         -0.666537784262792, -2.2360844549803156,
                                         -0.27497691778592454, -2.1743184927893937,
                                         -0.8629440316225654, -2.352121494766986,
                                         -1.6860226807044547, -0.61540971508612,
                                         -2.492550954914166, -1.468919291042873,
                                         -1.523032626446433, -2.3118408660453884,
                                         -2.607242282864573, -0.2780170188370663,
                                         -0.7406424947343584, -2.0188620459498727,
                                         -0.8325836135200276, -2.891613028556456,
                                         -2.3426585988376663, -2.2889449639023147,
                                         -2.2308326808157477, -3.012144432306056,
                                         -0.2539030483895336, -1.6738021359443653,
                                         -1.6768074221411653, -3.0115073902842435,
                                         -1.0213387352550833, -2.0638766514303826,
                                         -3.1174212805530574, -2.5987041143865013,
                                         -2.812716177130998, -0.5346056239435011,
                                         -3.2298078935442156, -2.089263815115461,
                                         -2.6157854702954735, -2.14544412744053,
                                         -2.9817096138127153, -2.5841540385451567,
                                         -2.4553754523874716, -0.9614511167957108,
                                         -1.7885263615631435, -2.5999574526580806,
                                         -2.2281982781343923, -2.157528414169483,
                                         -0.5921925467307219, -2.2742835265871424,
                                         -2.9156291882005894, -3.3624130571299347,
                                         -3.3649772609774855, -2.2105454193673566,
                                         -2.35712639233573, -1.467927245084475,
                                         -2.303876848830907, -1.8009736095081679,
                                         -3.320597303390881, -2.7839129792665673,
                                         -2.8056591345372164, -2.0088322628824757,
                                         -0.2047760516554033, -1.4551983766676884,
                                         -2.7779255406275523, -1.4553739687308591,
                                         -3.3622392805896455, -3.2600014755362485,
                                         -0.8576168736085746, -2.397979121157825,
                                         -2.3958442079597475, -2.9085882241445256,
                                         -1.9508251205983502, -2.316692658530843,
                                         -0.2833591067348137, -2.0126909196955,
                                         -2.664665720823435, -3.2409122748360772,
                                         -1.4698545233999183, -1.695833023437001,
                                         -0.7955027376245363, -2.3357478630299178,
                                         -2.166457446948672, -0.3347754997716007,
                                         -0.4156859972970325, -1.8095616881647103,
                                         -2.6821978195553022, -3.154673522026615,
                                         -2.561885570882366, -2.151435026028896,
                                         -2.514537244264697, -2.9911248933702175,
                                         -2.0836654559139562, -1.9091823621185067,
                                         -1.6522333991888314, -2.4038167322189645,
                                         -2.2310578141268658, -0.8697680780219145,
                                         -2.2679067787989085, -1.392472274101879,
                                         -1.0207503318898998, -3.028084367698452,
                                         -3.3769629945593422, -2.9127581705276135,
                                         -2.4049492613829315, -1.4689379579134014,
                                         -2.0070088818594627, -2.317963725892318,
                                         -2.1371951456541165, -0.8179389697272669,
                                         -2.679910069683042, -2.296674526691526,
                                         -3.1330145289245706, -2.505433292117909,
                                         -2.5062318202986797, -2.6749069000854617,
                                         -2.7949547305322113, -3.0255766190372055,
                                         -1.9088590609027953, -2.202776004701286,
                                         -2.2329743017387167, -3.233541636956302,
                                         -2.689697847559102, -2.6958428730715824,
                                         -2.502286808252186, -2.9845997523795385,
                                         -2.9033585467762864, -1.1820338372239045,
                                         -2.349631316680705, -1.8022472386086357,
                                         -1.9067423709311437, -2.263142639167328,
                                         -2.8958219133541006, -3.125415929173472]},
                             {'label': 'max_depth',
                              'range': [10, 50],
                              'values': [48, 16, 39, 18, 31, 15, 42, 11, 48, 14,
                                         30, 37, 17, 46, 18, 21, 32, 50, 43, 13,
                                         35, 23, 29, 33, 27, 36, 20, 13, 43, 17,
                                         46, 27, 30, 23, 38, 20, 11, 21, 30, 41,
                                         35, 44, 34, 19, 25, 14, 37, 19, 35, 46,
                                         13, 10, 16, 19, 40, 33, 20, 35, 30, 10,
                                         49, 48, 44, 22, 38, 50, 40, 22, 47, 36,
                                         23, 11, 34, 24, 18, 31, 50, 21, 49, 17,
                                         39, 40, 20, 14, 38, 29, 35, 35, 16, 34,
                                         36, 25, 12, 38, 10, 38, 42, 43, 41, 27,
                                         47, 46, 13, 33, 23, 42, 32, 14, 14, 43,
                                         50, 48, 13, 47, 29, 36, 25, 49, 46, 32,
                                         38, 46, 46, 17, 13, 31, 16, 39, 45, 43,
                                         25, 29, 45, 32, 20, 34, 24, 41, 32, 11,
                                         18, 34, 24, 35, 47, 50, 19, 16, 24, 17,
                                         21, 28, 38, 13, 21, 18, 25, 20, 31, 19,
                                         23, 46, 30, 40, 24, 50, 16, 21, 31, 26,
                                         20, 32, 17, 19, 33, 12, 50, 37, 26, 49,
                                         17, 44, 16, 31, 43, 22, 46, 35, 23, 31,
                                         22, 33, 43, 26, 39, 32, 47, 48, 35, 33]},
                             {'label': 'min_samples_leaf',
                              'range': [1, 32],
                              'values': [20, 28, 32, 6, 10, 12, 17, 6, 26, 15, 30,
                                         17, 25, 30, 11, 12, 26, 7, 24, 4, 3, 21,
                                         23, 16, 4, 17, 25, 6, 28, 18, 4, 28, 8,
                                         11, 32, 10, 17, 8, 8, 24, 18, 6, 1, 6, 5,
                                         29, 18, 29, 12, 25, 29, 22, 23, 8, 28, 12,
                                         13, 17, 24, 6, 12, 31, 13, 18, 4, 17, 23,
                                         26, 17, 26, 4, 18, 2, 17, 3, 21, 11, 3,
                                         23, 9, 9, 20, 25, 2, 4, 14, 2, 28, 21, 19,
                                         18, 29, 1, 11, 10, 29, 6, 14, 30, 25, 27,
                                         1, 31, 15, 25, 16, 29, 25, 23, 3, 12, 25,
                                         18, 16, 4, 19, 28, 32, 32, 17, 21, 9, 20,
                                         12, 32, 27, 27, 14, 1, 5, 27, 9, 32, 31,
                                         5, 22, 22, 28, 13, 20, 1, 14, 26, 31, 9,
                                         11, 5, 21, 16, 2, 3, 12, 26, 30, 24, 16,
                                         24, 29, 15, 13, 11, 22, 18, 5, 19, 8, 6,
                                         29, 32, 28, 22, 9, 14, 20, 16, 5, 26, 20,
                                         30, 24, 24, 26, 27, 29, 13, 17, 18, 31,
                                         26, 26, 24, 29, 28, 5, 21, 12, 13, 19, 28,
                                         30]},
                             {'label': 'min_samples_split',
                              'range': [2, 32],
                              'values': [24, 3, 2, 7, 15, 11, 8, 20, 31, 23, 3,
                                         11, 32, 20, 3, 27, 6, 25, 23, 13, 12, 24,
                                         5, 25, 2, 11, 14, 10, 21, 29, 11, 27, 14,
                                         31, 13, 17, 20, 30, 32, 9, 21, 11, 23, 22,
                                         31, 30, 27, 4, 12, 29, 7, 5, 19, 24, 22,
                                         4, 32, 26, 8, 22, 30, 15, 11, 7, 19, 6,
                                         23, 27, 17, 23, 13, 16, 2, 5, 21, 18, 18,
                                         15, 27, 6, 22, 19, 13, 3, 16, 7, 21, 17,
                                         4, 31, 16, 31, 5, 4, 27, 21, 10, 32, 12,
                                         25, 17, 14, 11, 21, 22, 4, 15, 6, 4, 23,
                                         13, 32, 26, 5, 3, 25, 10, 2, 18, 32, 16,
                                         3, 16, 16, 32, 11, 30, 21, 3, 32, 32, 14,
                                         27, 25, 15, 9, 5, 18, 29, 25, 6, 14, 17,
                                         28, 17, 17, 4, 6, 29, 7, 7, 8, 3, 29, 26,
                                         13, 16, 24, 5, 10, 8, 20, 4, 15, 22, 20,
                                         9, 7, 14, 32, 7, 19, 12, 5, 6, 12, 11, 25,
                                         12, 5, 4, 6, 7, 13, 15, 25, 13, 5, 6, 29,
                                         9, 25, 5, 26, 24, 9, 20, 6, 2, 23]},
                             {'label': 'n_estimators',
                              'range': [104, 997],
                              'values': [437, 240, 641, 850, 374, 651, 510, 633,
                                         158, 374, 209, 333, 592, 946, 179, 450,
                                         353, 167, 104, 794, 877, 380, 899, 785,
                                         570, 128, 917, 306, 937, 824, 827, 305,
                                         106, 207, 567, 967, 356, 146, 230, 705,
                                         431, 181, 136, 561, 722, 407, 332, 577,
                                         911, 754, 678, 646, 104, 687, 393, 692,
                                         338, 903, 619, 352, 947, 113, 968, 866,
                                         943, 654, 890, 423, 881, 819, 901, 621,
                                         358, 841, 793, 146, 754, 816, 122, 468,
                                         594, 960, 478, 112, 870, 542, 459, 437,
                                         693, 123, 449, 948, 276, 185, 861, 206,
                                         762, 776, 435, 873, 192, 388, 915, 956,
                                         364, 813, 151, 416, 657, 165, 176, 832,
                                         439, 482, 110, 205, 966, 301, 138, 166,
                                         667, 626, 956, 349, 625, 729, 716, 955,
                                         940, 439, 635, 855, 150, 997, 865, 959,
                                         656, 568, 597, 220, 734, 415, 914, 457,
                                         232, 513, 670, 215, 263, 701, 252, 208,
                                         553, 665, 155, 266, 657, 133, 561, 579,
                                         118, 207, 811, 628, 355, 420, 191, 268,
                                         172, 200, 836, 937, 793, 557, 360, 579,
                                         157, 329, 524, 848, 945, 617, 281, 699,
                                         453, 516, 309, 916, 665, 658, 236, 130,
                                         408, 214, 306, 725, 263, 516, 555, 939]}],
              'labelangle': 30,
              'labelside': 'bottom',
              'line': {'color': [-2.3072194221617885, -2.9031479297681897,
                                 -3.34043601971631, -1.0083653770417778,
                                 -1.5615423402515018, -1.7787617771463384,
                                 -2.188957250953307, -1.1171777215089826,
                                 -2.6883134271401516, -2.076962075628727,
                                 -3.116698589437815, -2.182227674095188,
                                 -2.584545609065986, -3.1339147590628396,
                                 -1.6778563950499579, -1.8352754631255082,
                                 -2.683718362811707, -1.3685735813073696,
                                 -2.493799603067955, -0.6598766446621787,
                                 -0.5239159718446803, -2.359782280925709,
                                 -2.4462335878145396, -2.1422565432728717,
                                 -0.5725293180744467, -2.184415736193736,
                                 -2.5876823402359035, -1.018816719538647,
                                 -2.8943997677575823, -2.2357553142340914,
                                 -0.6210069160223288, -2.8926227622897556,
                                 -1.3528044946102806, -1.827054466335659,
                                 -3.338276984155331, -1.5716972023000029,
                                 -2.1921175432707343, -1.5866459923281626,
                                 -1.6391120420421863, -2.523776784674328,
                                 -2.2485272338875992, -1.0280360587737774,
                                 -0.9691911423027555, -1.1672766796295586,
                                 -1.4236229804460807, -3.0170434417193426,
                                 -2.2341082903348677, -3.0128196874636384,
                                 -1.796891690379661, -2.5780904516292495,
                                 -3.044109060823282, -2.406291083787777,
                                 -2.479838788985392, -1.458242574336269,
                                 -2.904475034375764, -1.8005344530604455,
                                 -1.956290422872102, -2.18847130584661,
                                 -2.502538329755464, -1.1805050558466477,
                                 -1.8763651845010578, -3.260968701447736,
                                 -1.9018460665093222, -2.223192652528266,
                                 -0.8401654111829504, -2.187325210456301,
                                 -2.436566560697945, -2.6965001506339528,
                                 -2.189824222559378, -2.6851202325568613,
                                 -0.666537784262792, -2.2360844549803156,
                                 -0.27497691778592454, -2.1743184927893937,
                                 -0.8629440316225654, -2.352121494766986,
                                 -1.6860226807044547, -0.61540971508612,
                                 -2.492550954914166, -1.468919291042873,
                                 -1.523032626446433, -2.3118408660453884,
                                 -2.607242282864573, -0.2780170188370663,
                                 -0.7406424947343584, -2.0188620459498727,
                                 -0.8325836135200276, -2.891613028556456,
                                 -2.3426585988376663, -2.2889449639023147,
                                 -2.2308326808157477, -3.012144432306056,
                                 -0.2539030483895336, -1.6738021359443653,
                                 -1.6768074221411653, -3.0115073902842435,
                                 -1.0213387352550833, -2.0638766514303826,
                                 -3.1174212805530574, -2.5987041143865013,
                                 -2.812716177130998, -0.5346056239435011,
                                 -3.2298078935442156, -2.089263815115461,
                                 -2.6157854702954735, -2.14544412744053,
                                 -2.9817096138127153, -2.5841540385451567,
                                 -2.4553754523874716, -0.9614511167957108,
                                 -1.7885263615631435, -2.5999574526580806,
                                 -2.2281982781343923, -2.157528414169483,
                                 -0.5921925467307219, -2.2742835265871424,
                                 -2.9156291882005894, -3.3624130571299347,
                                 -3.3649772609774855, -2.2105454193673566,

In [40]:
optuna.visualization.plot_slice(study,params=['n_estimators','max_depth','min_samples_leaf','min_samples_split'])

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'marker': {'color': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
                                   14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
                                   26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
                                   38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
                                   50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
                                   62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
                                   74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
                                   86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
                                   98, 99, 100, 101, 102, 103, 104, 105, 106, 107,
                                   108, 109, 110, 111, 112, 113, 114, 115, 116,
                                   117, 118, 119, 120, 121, 122, 123, 124, 125,
                                   126, 127, 128, 129, 130, 131, 132, 133, 134,
                                   135, 136, 137, 138, 139, 140, 141, 142, 143,
                                   144, 145, 146, 147, 148, 149, 150, 151, 152,
                                   153, 154, 155, 156, 157, 158, 159, 160, 161,
                                   162, 163, 164, 165, 166, 167, 168, 169, 170,
                                   171, 172, 173, 174, 175, 176, 177, 178, 179,
                                   180, 181, 182, 183, 184, 185, 186, 187, 188,
                                   189, 190, 191, 192, 193, 194, 195, 196, 197,
                                   198, 199],
                         'colorbar': {'title': {'text': 'Trial'}, 'x': 1.0, 'xpad': 40},
                         'colorscale': [[0.0, 'rgb(247,251,255)'], [0.125,
                                        'rgb(222,235,247)'], [0.25,
                                        'rgb(198,219,239)'], [0.375,
                                        'rgb(158,202,225)'], [0.5,
                                        'rgb(107,174,214)'], [0.625,
                                        'rgb(66,146,198)'], [0.75,
                                        'rgb(33,113,181)'], [0.875,
                                        'rgb(8,81,156)'], [1.0, 'rgb(8,48,107)']],
                         'line': {'color': 'Grey', 'width': 0.5},
                         'showscale': True},
              'mode': 'markers',
              'name': 'Feasible Trial',
              'showlegend': False,
              'type': 'scatter',
              'x': [48, 16, 39, 18, 31, 15, 42, 11, 48, 14, 30, 37, 17, 46, 18,
                    21, 32, 50, 43, 13, 35, 23, 29, 33, 27, 36, 20, 13, 43, 17, 46,
                    27, 30, 23, 38, 20, 11, 21, 30, 41, 35, 44, 34, 19, 25, 14, 37,
                    19, 35, 46, 13, 10, 16, 19, 40, 33, 20, 35, 30, 10, 49, 48, 44,
                    22, 38, 50, 40, 22, 47, 36, 23, 11, 34, 24, 18, 31, 50, 21, 49,
                    17, 39, 40, 20, 14, 38, 29, 35, 35, 16, 34, 36, 25, 12, 38, 10,
                    38, 42, 43, 41, 27, 47, 46, 13, 33, 23, 42, 32, 14, 14, 43, 50,
                    48, 13, 47, 29, 36, 25, 49, 46, 32, 38, 46, 46, 17, 13, 31, 16,
                    39, 45, 43, 25, 29, 45, 32, 20, 34, 24, 41, 32, 11, 18, 34, 24,
                    35, 47, 50, 19, 16, 24, 17, 21, 28, 38, 13, 21, 18, 25, 20, 31,
                    19, 23, 46, 30, 40, 24, 50, 16, 21, 31, 26, 20, 32, 17, 19, 33,
                    12, 50, 37, 26, 49, 17, 44, 16, 31, 43, 22, 46, 35, 23, 31, 22,
                    33, 43, 26, 39, 32, 47, 48, 35, 33],
              'xaxis': 'x',
              'y': [-2.3072194221617885, -2.9031479297681897, -3.34043601971631,
                    -1.0083653770417778, -1.5615423402515018, -1.7787617771463384,
                    -2.188957250953307, -1.1171777215089826, -2.6883134271401516,
                    -2.076962075628727, -3.116698589437815, -2.182227674095188,
                    -2.584545609065986, -3.1339147590628396, -1.6778563950499579,
                    -1.8352754631255082, -2.683718362811707, -1.3685735813073696,
                    -2.493799603067955, -0.6598766446621787, -0.5239159718446803,
                    -2.359782280925709, -2.4462335878145396, -2.1422565432728717,
                    -0.5725293180744467, -2.184415736193736, -2.5876823402359035,
                    -1.018816719538647, -2.8943997677575823, -2.2357553142340914,
                    -0.6210069160223288, -2.8926227622897556, -1.3528044946102806,
                    -1.827054466335659, -3.338276984155331, -1.5716972023000029,
                    -2.1921175432707343, -1.5866459923281626, -1.6391120420421863,
                    -2.523776784674328, -2.2485272338875992, -1.0280360587737774,
                    -0.9691911423027555, -1.1672766796295586, -1.4236229804460807,
                    -3.0170434417193426, -2.2341082903348677, -3.0128196874636384,
                    -1.796891690379661, -2.5780904516292495, -3.044109060823282,
                    -2.406291083787777, -2.479838788985392, -1.458242574336269,
                    -2.904475034375764, -1.8005344530604455, -1.956290422872102,
                    -2.18847130584661, -2.502538329755464, -1.1805050558466477,
                    -1.8763651845010578, -3.260968701447736, -1.9018460665093222,
                    -2.223192652528266, -0.8401654111829504, -2.187325210456301,
                    -2.436566560697945, -2.6965001506339528, -2.189824222559378,
                    -2.6851202325568613, -0.666537784262792, -2.2360844549803156,
                    -0.27497691778592454, -2.1743184927893937, -0.8629440316225654,
                    -2.352121494766986, -1.6860226807044547, -0.61540971508612,
                    -2.492550954914166, -1.468919291042873, -1.523032626446433,
                    -2.3118408660453884, -2.607242282864573, -0.2780170188370663,
                    -0.7406424947343584, -2.0188620459498727, -0.8325836135200276,
                    -2.891613028556456, -2.3426585988376663, -2.2889449639023147,
                    -2.2308326808157477, -3.012144432306056, -0.2539030483895336,
                    -1.6738021359443653, -1.6768074221411653, -3.0115073902842435,
                    -1.0213387352550833, -2.0638766514303826, -3.1174212805530574,
                    -2.5987041143865013, -2.812716177130998, -0.5346056239435011,
                    -3.2298078935442156, -2.089263815115461, -2.6157854702954735,
                    -2.14544412744053, -2.9817096138127153, -2.5841540385451567,
                    -2.4553754523874716, -0.9614511167957108, -1.7885263615631435,
                    -2.5999574526580806, -2.2281982781343923, -2.157528414169483,
                    -0.5921925467307219, -2.2742835265871424, -2.9156291882005894,
                    -3.3624130571299347, -3.3649772609774855, -2.2105454193673566,
                    -2.35712639233573, -1.467927245084475, -2.303876848830907,
                    -1.8009736095081679, -3.320597303390881, -2.7839129792665673,
                    -2.8056591345372164, -2.0088322628824757, -0.2047760516554033,
                    -1.4551983766676884, -2.7779255406275523, -1.4553739687308591,
                    -3.3622392805896455, -3.2600014755362485, -0.8576168736085746,
                    -2.397979121157825, -2.3958442079597475, -2.9085882241445256,
                    -1.9508251205983502, -2.316692658530843, -0.2833591067348137,
                    -2.0126909196955, -2.664665720823435, -3.2409122748360772,
                    -1.4698545233999183, -1.695833023437001, -0.7955027376245363,
                    -2.3357478630299178, -2.166457446948672, -0.3347754997716007,
                    -0.4156859972970325, -1.8095616881647103, -2.6821978195553022,
                    -3.154673522026615, -2.561885570882366, -2.151435026028896,
                    -2.514537244264697, -2.9911248933702175, -2.0836654559139562,
                    -1.9091823621185067, -1.6522333991888314, -2.4038167322189645,
                    -2.2310578141268658, -0.8697680780219145, -2.2679067787989085,
                    -1.392472274101879, -1.0207503318898998, -3.028084367698452,
                    -3.3769629945593422, -2.9127581705276135, -2.4049492613829315,
                    -1.4689379579134014, -2.0070088818594627, -2.317963725892318,
                    -2.1371951456541165, -0.8179389697272669, -2.679910069683042,
                    -2.296674526691526, -3.1330145289245706, -2.505433292117909,
                    -2.5062318202986797, -2.6749069000854617, -2.7949547305322113,
                    -3.0255766190372055, -1.9088590609027953, -2.202776004701286,
                    -2.2329743017387167, -3.233541636956302, -2.689697847559102,
                    -2.6958428730715824, -2.502286808252186, -2.9845997523795385,
                    -2.9033585467762864, -1.1820338372239045, -2.349631316680705,
                    -1.8022472386086357, -1.9067423709311437, -2.263142639167328,
                    -2.8958219133541006, -3.125415929173472],
              'yaxis': 'y'},
             {'marker': {'color': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
                                   14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
                                   26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
                                   38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
                                   50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
                                   62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
                                   74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
                                   86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
                                   98, 99, 100, 101, 102, 103, 104, 105, 106, 107,
                                   108, 109, 110, 111, 112, 113, 114, 115, 116,
                                   117, 118, 119, 120, 121, 122, 123, 124, 125,
                                   126, 127, 128, 129, 130, 131, 132, 133, 134,
                                   135, 136, 137, 138, 139, 140, 141, 142, 143,
                                   144, 145, 146, 147, 148, 149, 150, 151, 152,
                                   153, 154, 155, 156, 157, 158, 159, 160, 161,
                                   162, 163, 164, 165, 166, 167, 168, 169, 170,
                                   171, 172, 173, 174, 175, 176, 177, 178, 179,
                                   180, 181, 182, 183, 184, 185, 186, 187, 188,
                                   189, 190, 191, 192, 193, 194, 195, 196, 197,
                                   198, 199],
                         'colorbar': {'title': {'text': 'Trial'}, 'x': 1.0, 'xpad': 40},
                         'colorscale': [[0.0, 'rgb(247,251,255)'], [0.125,
                                        'rgb(222,235,247)'], [0.25,
                                        'rgb(198,219,239)'], [0.375,
                                        'rgb(158,202,225)'], [0.5,
                                        'rgb(107,174,214)'], [0.625,
                                        'rgb(66,146,198)'], [0.75,
                                        'rgb(33,113,181)'], [0.875,
                                        'rgb(8,81,156)'], [1.0, 'rgb(8,48,107)']],
                         'line': {'color': 'Grey', 'width': 0.5},
                         'showscale': False},
              'mode': 'markers',
              'name': 'Feasible Trial',
              'showlegend': False,
              'type': 'scatter',
              'x': [20, 28, 32, 6, 10, 12, 17, 6, 26, 15, 30, 17, 25, 30, 11, 12,
                    26, 7, 24, 4, 3, 21, 23, 16, 4, 17, 25, 6, 28, 18, 4, 28, 8,
                    11, 32, 10, 17, 8, 8, 24, 18, 6, 1, 6, 5, 29, 18, 29, 12, 25,
                    29, 22, 23, 8, 28, 12, 13, 17, 24, 6, 12, 31, 13, 18, 4, 17,
                    23, 26, 17, 26, 4, 18, 2, 17, 3, 21, 11, 3, 23, 9, 9, 20, 25,
                    2, 4, 14, 2, 28, 21, 19, 18, 29, 1, 11, 10, 29, 6, 14, 30, 25,
                    27, 1, 31, 15, 25, 16, 29, 25, 23, 3, 12, 25, 18, 16, 4, 19,
                    28, 32, 32, 17, 21, 9, 20, 12, 32, 27, 27, 14, 1, 5, 27, 9, 32,
                    31, 5, 22, 22, 28, 13, 20, 1, 14, 26, 31, 9, 11, 5, 21, 16, 2,
                    3, 12, 26, 30, 24, 16, 24, 29, 15, 13, 11, 22, 18, 5, 19, 8, 6,
                    29, 32, 28, 22, 9, 14, 20, 16, 5, 26, 20, 30, 24, 24, 26, 27,
                    29, 13, 17, 18, 31, 26, 26, 24, 29, 28, 5, 21, 12, 13, 19, 28,
                    30],
              'xaxis': 'x2',
              'y': [-2.3072194221617885, -2.9031479297681897, -3.34043601971631,
                    -1.0083653770417778, -1.5615423402515018, -1.7787617771463384,
                    -2.188957250953307, -1.1171777215089826, -2.6883134271401516,
                    -2.076962075628727, -3.116698589437815, -2.182227674095188,
                    -2.584545609065986, -3.1339147590628396, -1.6778563950499579,
                    -1.8352754631255082, -2.683718362811707, -1.3685735813073696,
                    -2.493799603067955, -0.6598766446621787, -0.5239159718446803,
                    -2.359782280925709, -2.4462335878145396, -2.1422565432728717,
                    -0.5725293180744467, -2.184415736193736, -2.5876823402359035,
                    -1.018816719538647, -2.8943997677575823, -2.2357553142340914,
                    -0.6210069160223288, -2.8926227622897556, -1.3528044946102806,
                    -1.827054466335659, -3.338276984155331, -1.5716972023000029,
                    -2.1921175432707343, -1.5866459923281626, -1.6391120420421863,
                    -2.523776784674328, -2.2485272338875992, -1.0280360587737774,
                    -0.9691911423027555, -1.1672766796295586, -1.4236229804460807,
                    -3.0170434417193426, -2.2341082903348677, -3.0128196874636384,
                    -1.796891690379661, -2.5780904516292495, -3.044109060823282,
                    -2.406291083787777, -2.479838788985392, -1.458242574336269,
                    -2.904475034375764, -1.8005344530604455, -1.956290422872102,
                    -2.18847130584661, -2.502538329755464, -1.1805050558466477,
                    -1.8763651845010578, -3.260968701447736, -1.9018460665093222,
                    -2.223192652528266, -0.8401654111829504, -2.187325210456301,
                    -2.436566560697945, -2.6965001506339528, -2.189824222559378,
                    -2.6851202325568613, -0.666537784262792, -2.2360844549803156,
                    -0.27497691778592454, -2.1743184927893937, -0.8629440316225654,
                    -2.352121494766986, -1.6860226807044547, -0.61540971508612,
                    -2.492550954914166, -1.468919291042873, -1.523032626446433,
                    -2.3118408660453884, -2.607242282864573, -0.2780170188370663,
                    -0.7406424947343584, -2.0188620459498727, -0.8325836135200276,
                    -2.891613028556456, -2.3426585988376663, -2.2889449639023147,
                    -2.2308326808157477, -3.012144432306056, -0.2539030483895336,
                    -1.6738021359443653, -1.6768074221411653, -3.0115073902842435,
                    -1.0213387352550833, -2.0638766514303826, -3.1174212805530574,
                    -2.5987041143865013, -2.812716177130998, -0.5346056239435011,
                    -3.2298078935442156, -2.089263815115461, -2.6157854702954735,
                    -2.14544412744053, -2.9817096138127153, -2.5841540385451567,
                    -2.4553754523874716, -0.9614511167957108, -1.7885263615631435,
                    -2.5999574526580806, -2.2281982781343923, -2.157528414169483,
                    -0.5921925467307219, -2.2742835265871424, -2.9156291882005894,
                    -3.3624130571299347, -3.3649772609774855, -2.2105454193673566,
                    -2.35712639233573, -1.467927245084475, -2.303876848830907,
                    -1.8009736095081679, -3.320597303390881, -2.7839129792665673,
                    -2.8056591345372164, -2.0088322628824757, -0.2047760516554033,
                    -1.4551983766676884, -2.7779255406275523, -1.4553739687308591,
                    -3.3622392805896455, -3.2600014755362485, -0.8576168736085746,
                    -2.397979121157825, -2.3958442079597475, -2.9085882241445256,
                    -1.9508251205983502, -2.316692658530843, -0.2833591067348137,
                    -2.0126909196955, -2.664665720823435, -3.2409122748360772,
                    -1.4698545233999183, -1.695833023437001, -0.7955027376245363,
                    -2.3357478630299178, -2.166457446948672, -0.3347754997716007,
                    -0.4156859972970325, -1.8095616881647103, -2.6821978195553022,
                    -3.154673522026615, -2.561885570882366, -2.151435026028896,
                    -2.514537244264697, -2.9911248933702175, -2.0836654559139562,
                    -1.9091823621185067, -1.6522333991888314, -2.4038167322189645,
                    -2.2310578141268658, -0.8697680780219145, -2.2679067787989085,
                    -1.392472274101879, -1.0207503318898998, -3.028084367698452,
                    -3.3769629945593422, -2.9127581705276135, -2.4049492613829315,
                    -1.4689379579134014, -2.0070088818594627, -2.317963725892318,
                    -2.1371951456541165, -0.8179389697272669, -2.679910069683042,
                    -2.296674526691526, -3.1330145289245706, -2.505433292117909,
                    -2.5062318202986797, -2.6749069000854617, -2.7949547305322113,
                    -3.0255766190372055, -1.9088590609027953, -2.202776004701286,
                    -2.2329743017387167, -3.233541636956302, -2.689697847559102,
                    -2.6958428730715824, -2.502286808252186, -2.9845997523795385,
                    -2.9033585467762864, -1.1820338372239045, -2.349631316680705,
                    -1.8022472386086357, -1.9067423709311437, -2.263142639167328,
                    -2.8958219133541006, -3.125415929173472],
              'yaxis': 'y2'},
             {'marker': {'color': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
                                   14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
                                   26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
                                   38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
                                   50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
                                   62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
                                   74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
                                   86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
                                   98, 99, 100, 101, 102, 103, 104, 105, 106, 107,
                                   108, 109, 110, 111, 112, 113, 114, 115, 116,
                                   117, 118, 119, 120, 121, 122, 123, 124, 125,
                                   126, 127, 128, 129, 130, 131, 132, 133, 134,
                                   135, 136, 137, 138, 139, 140, 141, 142, 143,
                                   144, 145, 146, 147, 148, 149, 150, 151, 152,
                                   153, 154, 155, 156, 157, 158, 159, 160, 161,
                                   162, 163, 164, 165, 166, 167, 168, 169, 170,
                                   171, 172, 173, 174, 175, 176, 177, 178, 179,
                                   180, 181, 182, 183, 184, 185, 186, 187, 188,
                                   189, 190, 191, 192, 193, 194, 195, 196, 197,
                                   198, 199],
                         'colorbar': {'title': {'text': 'Trial'}, 'x': 1.0, 'xpad': 40},
                         'colorscale': [[0.0, 'rgb(247,251,255)'], [0.125,
                                        'rgb(222,235,247)'], [0.25,

In [41]:
optuna.visualization.plot_param_importances(study)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'cliponaxis': False,
              'hovertemplate': [max_depth (IntDistribution):
                                6.543207543731085e-05<extra></extra>, n_estimators
                                (IntDistribution):
                                9.336300066703028e-05<extra></extra>,
                                min_samples_split (IntDistribution):
                                0.00300443628118668<extra></extra>,
                                min_samples_leaf (IntDistribution):
                                0.996836768642709<extra></extra>],
              'name': 'Objective Value',
              'orientation': 'h',
              'text': [<0.01, <0.01, <0.01, 1.00],
              'textposition': 'outside',
              'type': 'bar',
              'x': [6.543207543731085e-05, 9.336300066703028e-05,
                    0.00300443628118668, 0.996836768642709],
              'y': [max_depth, n_estimators, min_samples_split, min_samples_leaf]}],
    'layout': {'template': '...',
               'title': {'text': 'Hyperparameter Importances'},
               'xaxis': {'title': {'text': 'Hyperparameter Importance'}},
               'yaxis': {'title': {'text': 'Hyperparameter'}}}
})

In [52]:
best_n_estimator=best_params['n_estimators']
best_max_depth=best_params['max_depth']
best_min_samples_split=best_params['min_samples_split']
best_min_samples_leaf=best_params['min_samples_leaf']

In [55]:
best_model=RandomForestRegressor(
    n_estimators=best_n_estimator,
                                 max_depth=best_max_depth,
                                 min_samples_split=best_min_samples_split,
                                 min_samples_leaf=best_min_samples_leaf)

In [56]:
best_model.fit(X_Train,y_train)

RandomForestRegressor(max_depth=45, min_samples_split=3, n_estimators=940)

In [57]:
y_pred=best_model.predict(X_test)

In [58]:
mean_absolute_error(y_pred,y_test)

0.320518835006548

In [59]:
mean_squared_error(y_test,y_pred)

0.1648343111109212

In [60]:
r2_score(y_test,y_pred)

0.9826206928976002