In [1]:
import pandas as pd

In [5]:
import pandas as pd

d = {
    'sales': [100000, 222000, 1000000, 522000, 111111,222222,1111111,20000],
    'city': ['Tampa', 'Tampa', 'Orlando', 'Jacksonville', 'Miami','Jacksonville','Miami','Miami'],
    'size': ['Small', 'Medium', 'Large', 'Large', 'Small','Medium','Large','Small']
}

df = pd.DataFrame(data=d)

df.head(8)

     sales          city    size
0   100000         Tampa   Small
1   222000         Tampa  Medium
2  1000000       Orlando   Large
3   522000  Jacksonville   Large
4   111111         Miami   Small
5   222222  Jacksonville  Medium
6  1111111         Miami   Large
7    20000         Miami   Small

In [10]:
df['city'].unique()

<ArrowStringArray>
['Tampa', 'Orlando', 'Jacksonville', 'Miami']
Length: 4, dtype: str

In [ ]:
from sklearn.preprocessing import OneHotEncoder

1. OneHotEncoder(...) Nedir?
Bilgisayarlar "Kırmızı", "Mavi", "Yeşil" gibi kelimelerden anlamaz; sayılarla konuşur. One-Hot Encoding, her kategoriyi ayrı bir sütuna dönüştürür.

Örnek: "Renk" sütununda 3 seçenek varsa, bunu 3 farklı sütuna (Renk_Kırmızı, Renk_Mavi, Renk_Yeşil) böler. O satır hangi renkse oraya 1, diğerlerine 0 yazar.


""" handle_unknown='ignore'	Hayat kurtarır. Eğer model eğitilirken görmediği yeni bir kategoriyle (mesela test verisinde "Sarı" gelirse) karşılaşırsa hata vermek yerine o satır için tüm sütunlara 0 basar ve geçer.


sparse_output=False	Normalde bu işlem "sparse matrix" (seyrek matris) döndürür (bellekten tasarruf için). Ama biz bunu False yaparak doğrudan okunabilir, yoğun bir dizi (numpy array) veya tablo istiyoruz.


.set_output(transform='pandas')	En can alıcı nokta burası. Eskiden bu işlemden sonra sütun isimleri kaybolur, elimizde isimsiz bir s
sayı yığını kalırdı. Bu komut sayesinde çıktı doğrudan bir Pandas DataFrame olarak döner ve sütun isimleri (örn: Renk_Kırmızı) otomatik eklenir."""

In [ ]:
ohe=OneHotEncoder(handle_unknown='ignore', sparse_output=False).set_output(transform='pandas')

#sparse_outpu dataframe olarak çıksın diye

In [ ]:
ohetransform= ohe.fit_transform(df[['city']])
ohetransform

   city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0                0.0         0.0           0.0         1.0
1                0.0         0.0           0.0         1.0
2                0.0         0.0           1.0         0.0
3                1.0         0.0           0.0         0.0
4                0.0         1.0           0.0         0.0
5                1.0         0.0           0.0         0.0
6                0.0         1.0           0.0         0.0
7                0.0         1.0           0.0         0.0

In [23]:
df.head()

     sales          city    size
0   100000         Tampa   Small
1   222000         Tampa  Medium
2  1000000       Orlando   Large
3   522000  Jacksonville   Large
4   111111         Miami   Small

In [24]:
df=pd.concat([df,ohetransform], axis=1).drop(columns='city')

In [25]:
df

     sales    size  city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0   100000   Small                0.0         0.0           0.0         1.0
1   222000  Medium                0.0         0.0           0.0         1.0
2  1000000   Large                0.0         0.0           1.0         0.0
3   522000   Large                1.0         0.0           0.0         0.0
4   111111   Small                0.0         1.0           0.0         0.0
5   222222  Medium                1.0         0.0           0.0         0.0
6  1111111   Large                0.0         1.0           0.0         0.0
7    20000   Small                0.0         1.0           0.0         0.0